{{- if not .Values.secrets.existingSecret }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ include "streamingapp.secretName" . }}
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}

type: Opaque

stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}

  MONGO_URI: {{ include "streamingapp.mongoUri" . | quote }}

  {{- if .Values.secrets.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  {{- end }}

  {{- if .Values.secrets.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  {{- end }}

{{- end }}
